### ISSUE TITLE
cannot load such file -- kramdown/parser/kramdown (LoadError)

### ISSUE THREAD

**Issue by ledestin** [piotrmurach/tty-markdown#10]
### Describe the problem
I was excited about having nicely formatted markdown, but unfortunately I'm getting an error `cannot load such file -- kramdown/parser/kramdown (LoadError)`, when I run the code below.

### Steps to reproduce the problem
```
echo hi | ruby -rtty-markdown -e 'puts TTY::Markdown.parse($stdin.read)'
```

### Actual behaviour
Exception raised.

### Expected behaviour
Formatted markdown output.

### Describe your environment

* OS version: Debian 9.8
* Ruby version: 2.5.3p105
* TTY::Markdown version: 0.5.1

**Comment by piotrmurach** [comment]
Hi Dmitry,

Thanks for trying the `tty-markdown`. 

Your example works fine for me. Have you installed the `tty-markdown` gem? The `kramdown` is a core dependency that gets installed with the gem.

```ruby
gem install tty-markdown
````

**Comment by ledestin** [comment]
Sorry, I forgot to include the stacktrace, but sure I have it installed. If I hadn't, the error would be about that.

But it was my own mistake, I have `ruby` use `bundle exec` by default, so that's why it failed.
