### ISSUE TITLE
Formatting is broken inside blockquotes

### ISSUE THREAD

**Issue by zverok** [piotrmurach/tty-markdown#11]
```ruby
str = "> **London (/ˈlʌndən/ (About this soundlisten) LUN-dən) is the capital and largest city of both England and the United Kingdom. Standing on the River Thames in the south-east of England, at the head of its 50-mile (80 km) estuary leading to the North Sea, London has been a major settlement for two millennia.**"

puts TTY::Markdown.parse(str)
```

Result:
![image](https://user-images.githubusercontent.com/129656/56026875-c01be880-5d1d-11e9-8dda-19a936697883.png)

Things to notice:
1. The text seems to be split into lines before adding `|  ` at the beginning, so its size is now slightly larger than terminal width
2. "Bold" formatting now relates only to the first line of splitted text.

**Comment by zverok** [comment]
And one more:
```ruby
puts TTY::Markdown.parse("> I try it this way.\nBut it's not good.")
```
prints:
```
┃  I try it this way.
┃  But it
┃  ’s not good.
```
(notice unwanted linebreak before `’`)

**Comment by piotrmurach** [comment]
Hey Victor

Thanks for reporting this! 🙇 

The first issue is partially related to my other gem `strings` and the [wrap](https://github.com/piotrmurach/strings#27-wrap) call. Wrapping multiline content with ANSI codes proves to be a bit harder than I expected, there are quite a few corner cases.

**Comment by piotrmurach** [comment]
All the described issues are fixed:

![tty-markdown-blockquote-fix](https://user-images.githubusercontent.com/444312/91218046-651b4380-e710-11ea-944f-855876444c55.png)
