### ISSUE TITLE
Printing markdown directly from console

### ISSUE THREAD

**Issue by bogn83** [piotrmurach/tty-markdown#12]
Thanks for the awesome gem! Using your template here, otherwise I wouldn't speak of problem or expected behavior.

### Describe the problem
Currently there is no built-in way to print parsed markdown directly to the terminal without using custom scripts. This would be a nice feature.

### Expected behaviour
$ tty-markdown README.md
**Hello Ruby**

### One way to do it
This is not necessarily a portable or good solution since it's not extendable or anything and doesn't print help, but for the time being I'm currently putting this script into my $PATH which can take a file name or STDIN:
```ruby
#!/usr/bin/env ruby

require 'tty-markdown'

if ARGV[0]
    content = File.read(File.expand_path(ARGV[0]))
else
    content = $stdin.read
end

puts TTY::Markdown.parse(content)
```

If you want to rather not go that route, you might also put this script or something similar to the wiki.

**Comment by piotrmurach** [comment]
Hi Bogomir,

Thank you for using the library! I know this is super late. But hopefully my answer is of some use.

I think this is a good idea but I'm not sure how to handle it. My usual stance of things like this is to have a separate gem that comes with an executable. Why? I don't believe that general tools like `tty-markdown` should be packaged with executables. People who want to use `tty-markdown` to build their own tools would be required to download an executable and by proxy their users. Unless you're building a tool that primary goal is to serve a binary, e.i. `rspec` or `bundler` I think it's better to leave it out.

As a middle ground, for now, I would accept a PR that adds this to docs to help people get started. Do you have time to cook something up?
