### ISSUE TITLE
Syntax highlighten broken when a blank newline exists in code

### ISSUE THREAD

**Issue by ianks** [piotrmurach/tty-markdown#13]
### Describe the problem
Syntax highlight does not work when a blank newline is used in the code.

### Steps to reproduce the problem
here is a reproducable test case: https://gist.github.com/ianks/7ef16af7a2c85d8833e523a2a25ba0a0

### Actual behaviour
The code is not highlighted

### Expected behaviour
The code to be highlighted

### Describe your environment
* OS version: Linux 5.2.9-arch1-1-ARCH
* Ruby version: 2.6.2
* TTY::Markdown version: 0.6.0

**Comment by piotrmurach** [comment]
Hi Ian,

Thanks for using `tty-markdown` and reporting this issue. 🙏 

Would you have time to submit a test case in [codeblock_spec.rb](https://github.com/piotrmurach/tty-markdown/blob/master/spec/unit/parse/codeblock_spec.rb). This maybe an issue with `tty-markdown` or the `kramdown` parser. Not sure at this stage but would be keen to get this fixed.

**Comment by piotrmurach** [comment]
I had some time to investigate and it turns out this is to do with default `kramdown` parser which doesn't handle newlines in fenced codeblocks. However, when you switch over to use `GFM` parser then this starts to work.
