### ISSUE TITLE
Link labels are not displayed when they don't contain single or double quotes

### ISSUE THREAD

**Issue by krage** [piotrmurach/tty-markdown#14]
### Describe the problem
Links in output are not labeled when the markdown square-bracketed label both isn't blank and doesn't contain at least one single quote or double quote character.  Noticed this when virtually none of the links in samples I was trying were being produced with labels.

### Steps to reproduce the problem
Starting with the examples from current spec which pass:
```ruby
TTY::Markdown.parse("[I'm an inline-style link](https://www.google.com)")
=> "I’m an inline-style link » \e[33;4mhttps://www.google.com\e[0m\n"
TTY::Markdown.parse("[I'm an inline-style link with title](https://www.google.com \"Google's Homepage\")")
=> "Google's Homepage » \e[33;4mhttps://www.google.com\e[0m\n"
```
Tried a variety of modified labels in the square brackets and so far it appears anything that is both not blank and does not include at least one `'` or `"` results in no `label » ` being produced in the output.
eg:
```ruby
# just the single-quote removed from spec => no label
TTY::Markdown.parse("[Im an inline-style link](https://www.google.com)")
=> "\e[33;4mhttps://www.google.com\e[0m\n"
# just the single-quote removed from spec => no label
TTY::Markdown.parse("[Im an inline-style link with title](https://www.google.com \"Google's Homepage\")")
=> "\e[33;4mhttps://www.google.com\e[0m\n"
# completely blank => has label
TTY::Markdown.parse("[](https://www.google.com)")
=> " » \e[33;4mhttps://www.google.com\e[0m\n"
# single char but no quote => no label
TTY::Markdown.parse("[x](https://www.google.com)")
=> "\e[33;4mhttps://www.google.com\e[0m\n"
# just a single-quote => has label
TTY::Markdown.parse("['](https://www.google.com)")
=> "’ » \e[33;4mhttps://www.google.com\e[0m\n"
# just a double-quote => has label
TTY::Markdown.parse("[\"](https://www.google.com)")
=> "” » \e[33;4mhttps://www.google.com\e[0m\n"
# emoji => no label
TTY::Markdown.parse("[👋](https://www.google.com)")
=> "\e[33;4mhttps://www.google.com\e[0m\n"
```

### Describe your environment

* OS version: Tried both Ubuntu 18.04 and Windows 10
* Ruby version: 2.6.5p114 (2019-10-01 revision 67812)
* TTY::Markdown version: 0.6.0

**Comment by piotrmurach** [comment]
Hi, 

Thanks for using the library and reporting the issue. 🙏 

Would you have time to convert your examples into test cases and add them to [link_spec.rb](https://github.com/piotrmurach/tty-markdown/blob/master/spec/unit/parse/link_spec.rb)? If you have time to fix this issue as well that would be great! However, just test cases will be of help. I cannot say whether this is an issue with `tty-markdown` itself or the `kramdown` parsing of markdown content.

**Comment by krage** [comment]
I've had a look and it looks to me like just an implementation issue on the `tty-markdown` end.

https://github.com/piotrmurach/tty-markdown/blob/71f6a1a0b20a9beb07445dc4d21e8d6dbfd3a341/lib/tty/markdown/parser.rb#L417-L432

If the link tag coming in from `kramdown` has exactly 1 child `:text` element then no label will be emitted.  This condition immediately matches the majority of those problem examples I looked at previously.  The examples including quotes don't fall into this trap because they end up having at least 1 `:rsquo` or `:rdquo` child element.

This may be too significant of a change but I'd propose replacing with something like this:
```ruby
def convert_a(el, opts)
  symbols = TTY::Markdown.symbols
  styles = Array(@theme[:link])
  if el.children.size > 1 || el.children.size == 1 && (el.children[0].type != :text || !el.children[0].value.strip.empty?)
    inner(el, opts)
    if el.attr['title']
      opts[:result] << " #{symbols[:arrow]}(#{el.attr['title']}) "
    else
      opts[:result] << " #{symbols[:arrow]} "
    end
    opts[:result] << @pastel.decorate(el.attr['href'], *styles)
  end
end
```
This fixes the circumstances where labels were missing and also makes some behavior changes that I think would be more consistent with the visible output from typical markdown HTML rendering:
1. If the label is effectively empty/whitespace then don't display the link at all, eg. `[](https://example.com)` typically produces an HTML anchor tag containing no text/children and thus isn't visible when rendered in a browser.
2. If a title attr is present display it in addition to rather than instead of the label, eg. for `[Label](https://example.com \"Title\")` the Title doesn't replace Label, both are displayed: `Label »(Title) https://example.com`.

I bumped into a couple additional quick fix issues while poking around at this.
1. If the label is at least two spaces followed by a newline `kramdown` produces a `:br` as part of the children set which `tty-markdown` currently doesn't handle at all resulting in a `NoMethodError` as `convert_br` isn't defined.
2. I noticed that on Windows quote characters weren't actually being produced in the output but the tests were still passing.  It turns out in the `WIN_SYMBOLS` hash the `:lsquo` and `:rsquo` values are being [defined as unescaped regular single quotes surrounded by single quotes](https://github.com/piotrmurach/tty-markdown/blob/71f6a1a0b20a9beb07445dc4d21e8d6dbfd3a341/lib/tty/markdown.rb#L53-L54) aka groups of three single quotes leading to `:lsquo` having the value `,\n      rsquo: ` while `:rsquo` is `nil`.  It might also be worth updating `WIN_SYMBOLS` as a whole since as far as I can tell Windows 10's command prompt & built-in fonts support nearly all the characters used in the nicer regular `SYMBOLS` table out of the box.

I can probably wrap all this up with those added tests in a PR if you like.

**Comment by piotrmurach** [comment]
Thanks for investigating the issue. I'm totally in for some PRs!

Would it be possible for you to submit separate PRs for all the three issues. Why? It's easier to review and merge things individually. The `convert_br` and links seem more straightforward but the links may require small tweaks. For example, your example skips handling of newline. Not sure why. It may be that it is no longer needed but as far as I recall that's important for longer output to be properly formatted. There can be more things to iron out. Especially the windows thing is usually a bit problematic. Anyhow please submit away and I will respond quickly.

**Comment by piotrmurach** [comment]
Ohh one more thing, I created [tty-link](https://github.com/piotrmurach/tty-link) some time ago and I'm thinking whether it would be a good idea to use it here. Any thoughts?

**Comment by krage** [comment]
Sure can definitely submit as separate PRs.

I was initially thinking inserting a newline after every link was unnecessarily modifying the layout.  If there are formatting consequences perhaps it could be specified as an option?

I'm not using any of the terminals supported by tty-link so I'm not ready to integrate it myself but it looks like a nice future enhancement.
