### ISSUE TITLE
Ruby 2.7 compatibility: keyword parameters deprecation

### ISSUE THREAD

**Issue by DannyBen** [piotrmurach/tty-markdown#23]
### Problem

Running in Ruby 2.7 triggers deprecation warnings to stderr.

This seems to be already fixed in master:

https://github.com/piotrmurach/tty-markdown/blob/fb0b90332b49457ad6d54c3f87add63e71e5df97/lib/tty/markdown/parser.rb#L15

Compared to the code in 0.6.0

https://github.com/piotrmurach/tty-markdown/blob/71f6a1a0b20a9beb07445dc4d21e8d6dbfd3a341/lib/tty/markdown/parser.rb#L15

Any chance of an upcoming 0.6.1 release?

### Reproduction code

```
require 'tty-markdown'
puts TTY::Markdown.parse("# Hello")
```

### Error

```
/gems/ruby-2.7.0/gems/kramdown-1.16.2/lib/kramdown/converter/base.rb:102: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/gems/ruby-2.7.0/gems/tty-markdown-0.6.0/lib/tty/markdown/parser.rb:15: warning: The called method `initialize' is defined here
```

### Describe your environment

* OS version: Ubuntu
* Ruby version: 2.7.0p9
* TTY::Markdown version: 0.6.0

**Comment by piotrmurach** [comment]
This is fixed in the master branch. However, I cannot release the `0.7.0` version since it changes how the markdown parser works and I haven't settled on the final result. I'll see if I have time to fork and make `0.6.1` release.
