### ISSUE TITLE
Spaces around inline code quotes collapses inside list items

### ISSUE THREAD

**Issue by maetl** [piotrmurach/tty-markdown#9]
Inline code quotes (backticks) seem to be working fine in normal paragraph text, but when the text is included in list items, the spaces around the backtick quotes are collapsing.

### Quote inside paragraph

```ruby
test_str = "To check which version, run `ruby -v` or `ruby --version`."

print TTY::Markdown.parse(test_str)
```

#### Actual Result ✅

![image](https://user-images.githubusercontent.com/24809/52185312-3a923d00-2883-11e9-8dd7-55bcf379c525.png)

### Quotes inside list items

```ruby
test_str = [
  "- Version: run `ruby -v` or `ruby --version`.",
  "- Help: run `ruby -h` or `ruby --help`."
].join("\n")

print TTY::Markdown.parse(test_str)
```

#### Actual Result ❌

![image](https://user-images.githubusercontent.com/24809/52185362-c3a97400-2883-11e9-8940-6ef6b9e51557.png)

### Environment

* OS version: macOS
* Ruby version: 2.4–2.6
* TTY::Markdown version: 0.5.0

**Comment by maetl** [comment]
I noticed in `TTY::Markdown::Parser#convert_p`, [there is an option being set](https://github.com/piotrmurach/tty-markdown/blob/master/lib/tty/markdown/parser.rb#L83) that seems to be related to this issue.

I tried changing the option:

```ruby
# Current state
opts[:strip] = true

# Suggested change
opts[:strip] = false
```

This seems to fix the above issue. I have no idea yet if it causes problems elsewhere.

**Comment by piotrmurach** [comment]
Released `v0.5.1` with the fix.

**Comment by piotrmurach** [comment]
Btw, that was a really good report that made it possible to fix the issue quickly ❤️

**Comment by maetl** [comment]
Brilliant, thank you!
